### ISSUE TITLE
Name of some buttons in the preset

### ISSUE THREAD

**Issue by holyrics** [bitfocus/companion-module-limagiran-holyrics#3]
Hi!

The name "Hide slides" (close current presentation) could be "close" or "exit", as "Hide slides" can cause confusion with the option F9 (empty slide)

I believe that the `wallpaper`, `empty slide` and `black screen` buttons could be displayed without the "Toggle" prefix

Thanks!

**Comment by JeLuF** [comment]
> The name "Hide slides" (close current presentation) could be "close" or "exit", as "Hide slides" can cause confusion with the option F9 (empty slide)

F9 hides the _content_ of the slide, but not the slide itself. Its background is still being displayed. 

For me, "exit" sounds like closing the Holyrics application (Alt-F4), and also "close" on its own would be very close to "exit". "Close presentation" would work - but it's pretty long.

> I believe that the wallpaper, empty slide and black screen buttons could be displayed without the "Toggle" prefix

Yes, that might be. I personally prefer to have verbs as label, not nouns.

**Comment by JeLuF** [comment]
![image](https://github.com/bitfocus/companion-module-limagiran-holyrics/assets/5852422/06877630-738e-4e3d-a90e-6a034af309f5)
Would this be a self-explanatory icon for close/exit/hide slides/?

**Comment by holyrics** [comment]
> ![image](https://private-user-images.githubusercontent.com/5852422/323759591-06877630-738e-4e3d-a90e-6a034af309f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzQ4ODMsIm5iZiI6MTcxMzQ3NDU4MywicGF0aCI6Ii81ODUyNDIyLzMyMzc1OTU5MS0wNjg3NzYzMC03MzhlLTRlM2QtYTkwZS02YTAzNGFmMzA5ZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMjEwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzhlNDI1MzJjOTk0Njg1MWRhNTRiOWRhYmNmMTJiYmNiMGI2NGE3MDMyNGMzNjE3NWM1ZTNjOTlhMWViZTZhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mmNe5ATCZjEvyIxRoZ7rrSLLmcNk4EKbaz-xBBkOqcU) Would this be a self-explanatory icon for close/exit/hide slides/?

Yes, it looks great!
<br>
> Yes, that might be. I personally prefer to have verbs as label, not nouns.

I also give preference to verbs, the suggestion to remove the "toggle" prefix in this case is just because of the number of words in the button, as it would be 3 words.
