### ISSUE TITLE
MediaPlayer - request for new actions

### ISSUE THREAD

**Issue by holyrics** [bitfocus/companion-module-limagiran-holyrics#5]
Hi!

I would like to suggest these actions for MediaPlayer, please
`mute`, `repeat`, `execute_single`, `fullscreen`

```javascript
//poll.js
self.state['mp_mute'] = mediaPlayer?.data?.mute == true
self.state['mp_repeat'] = mediaPlayer?.data?.repeat == true
self.state['mp_execute_single'] = mediaPlayer?.data?.execute_single == true
self.state['mp_fullscreen'] = mediaPlayer?.data?.fullscreen == true

//actions.js
self.do_command('MediaPlayerAction', { mute: !self.state['mp_mute'] );
self.do_command('MediaPlayerAction', { repeat: !self.state['mp_repeat'] );
self.do_command('MediaPlayerAction', { execute_single: !self.state['mp_execute_single'] );
self.do_command('MediaPlayerAction', { fullscreen: !self.state['mp_fullscreen'] );
```

A brief explanation:
the `repeat` option is self-explanatory, it works like every standard player.
However, it makes a difference when used in conjunction with `execute_single`, which is to define whether to execute only the player's current item `(execute_single=true)` and stop execution or whether to execute the player's entire current list, i.e., go to the next item in the list `(execute_single=false)` when finishing the current executing item.

Thanks!

**Comment by JeLuF** [comment]
![image](https://github.com/bitfocus/companion-module-limagiran-holyrics/assets/5852422/b3647a5d-8887-4f20-99b2-978131a6252f)
