### ISSUE TITLE
New action request - ActionGoToSlideDescription

### ISSUE THREAD

**Issue by holyrics** [bitfocus/companion-module-limagiran-holyrics#6]
Hi!

I would like to suggest implementing the `ActionGoToSlideDescription` action

```javascript
self.do_command('ActionGoToSlideDescription', { name: 'Slide Description Name' })
```
This action can be performed while displaying a song lyric.
If the user has defined the description for the song lyrics slides, this action will advance/back the current presentation to the corresponding slide.

Some recommended names for preset creation
`Chorus` `Verse` `PreChorus` `Intro` `Brigde` `Tag` `End` `Verse 1` `Verse 2` `Verse 3` `Verse 4`

Regarding the slide description, when editing the song lyrics they are displayed like this

```
##(Verse 1)
Example example

##(Chorus)
Example example

##(Verse 2)
Example example

##(Verse 3)
Example example
```

Thanks!

**Comment by JeLuF** [comment]
On version 2.21.1:

I've set up a song with slide descriptions:
![image](https://github.com/bitfocus/companion-module-limagiran-holyrics/assets/5852422/81ba8639-41c2-40f9-a478-2ab1213790a1)

I then try to go to the slide:
```
curl -s 'http://localhost:8091/api/ActionGoToSlideDescription?token=b3jd28Rqf7bxU9BB' -X POST -H 'Content-Type: application/json'  -d '{"name": "Chorus"}'

{"status":"error","error":"Slide description \u0027Chorus\u0027 not found"}      
```   

Should this work on 2.21.1, or is this a new feature? I'll set up a 2.22 system later today and will double check.

**Comment by holyrics** [comment]
I verified here that it is a cache problem.
User-created descriptions are only identified after opening the "slide description" window at least once.
file menu - settings - public tab - slide description button

Or in the "settings" item in the context menu of that example image you sent.

I'll make a note to fix it in the next update.
It's an inconvenience, I don't know what the impact of this error could be for users currently, that is, what proportion of users would use this option and who never opened this "slide description" configuration window.
If you think it's better, you can leave it pending for future updates, or if it's possible in the companion ecosystem, add an option that displays a notification to the user when this error occurs

> Should this work on 2.21.1, or is this a new feature? I'll set up a 2.22 system later today and will double check.

Just for information (but I think you already know), you can make copies of the program folder `C:\Holyrics` if you want to have multiple versions available, this way it is easier to manage different versions.
Just open the Holyrics.exe program from its respective subfolder, each program runs independently of the other, as the data is in the program's own subfolder.

**Comment by JeLuF** [comment]
> Just for information (but I think you already know), you can make copies of the program folder C:\Holyrics if you want to have multiple versions available, this way it is easier to manage different versions.

I noticed that the installation path is hardcoded to `C:\Holyrics` and assumed that this is due to hardcoded paths within the application, so that I assumed that moving Holyrics to a different directory would actually break it.

**Comment by JeLuF** [comment]
> I verified here that it is a cache problem.

Caching is the root of all evil.

After going to the settings, it works. I will put this issue 'on hold' until you fixed it in Holyrics.

**Comment by holyrics** [comment]
> > Just for information (but I think you already know), you can make copies of the program folder C:\Holyrics if you want to have multiple versions available, this way it is easier to manage different versions.
> 
> I noticed that the installation path is hardcoded to `C:\Holyrics` and assumed that this is due to hardcoded paths within the application, so that I assumed that moving Holyrics to a different directory would actually break it.

I blocked changing the file location on installation because many users could select the "program files" folder as the installation location, and it would be a problem, because the program could not save data in the subfolder itself, only if it was run as administrator. And since the goal was to maintain the program's file structure by saving data in its own subfolder, I needed to select a neutral location, like C:\Holyrics, and lock the location in the installation window just in case.

But the program is standalone and 100% portable, you can even copy the folder to a flash drive or external HD and it will work, without the need for installation.

**Comment by holyrics** [comment]
> > I verified here that it is a cache problem.
> 
> Caching is the root of all evil.

Well noted! 😄 

 
> After going to the settings, it works. I will put this issue 'on hold' until you fixed it in Holyrics.

OK thanks!

**Comment by holyrics** [comment]
> After going to the settings, it works. I will put this issue 'on hold' until you fixed it in Holyrics.

Hi!

Just to let you know, last week there was a need for a 2.22.1 patch update, so this issue reported here is already fixed in the current production version of Holyrics.

**Comment by holyrics** [comment]
Hi!

I saw that you implemented the action.
Thanks!

In Portuguese we use the word `Verso` to indicate a verse of the song.
We use `Versículo` when it is a verse from the Bible specifically.

```javascript
const tags = ['Chorus', 'Verse', 'PreChorus', 'Intro', 'Bridge', 'Tag', 'End', 
        'Verse 1', 'Verse 2', 'Verse 3', 'Verse 4', 'Verse 5', 'Verse 6', 'Verse 7', 'Verse 8', 'Verse 9', 
        'Refrão', 'Coro', 'Verso', 'Pré-Coro', 'Introdução', 'Ponte', 'Final', 
        'Verso 1', 'Verso 2', 'Verso 3', 'Verso 4', 'Verso 5', 'Verso 6', 'Verso 7', 'Verso 8', 'Verso 9']
```

I forgot to comment, I don't know if you can create presets based on some value returned in the current connection or if the presets are fixed, created before a connection, but it is possible to use the `GetSlideDescriptions` action to obtain the list of descriptions available for being able to create presets based on those the user already has available.

**Comment by JeLuF** [comment]
We have the same in German, 'Strophe' for songs, 'Vers' for bible verses. I used google translate German->Portuguese. But apparently, Google went via English and messed it up. I should have used a dictionary :-(

If I remember correctly, I can recreate the presets when the connection is established. I'll have a look.
